#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const child_process = require('child_process');

const build = directory =>
  require([
    `./${path.join(directory, 'build.js')}`,
    `./${path.join(directory.replace(/^\.\/ru($|\/)/, ''), 'build.js')}`,
    './lib/build.js',
  ].find(module => fs.existsSync(module)))(directory);

const directories = () =>
  process.argv.length > 2
    ? process.argv.slice(2)
    : child_process
        .spawnSync(
          'find',
          [
            '-type',
            'd',
            '!',
            '-regex',
            String.raw`\./\(\..+\|node_modules\)\(\|/.+\)`,
          ],
          { encoding: 'utf8' },
        )
        .stdout.split('\n')
        .slice(0, -1);

const main = () =>
  directories().forEach(directory => {
    const html = build(directory);
    if (html !== undefined) {
      fs.writeFileSync(path.join(directory, 'index.html'), html);
    }
  });

main();
